[package]
name = "ui-bin"
version = "0.0.1"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "The Air Artificial General Intelligence"
homepage = "https://github.com/LambdaAlpha/ui-doc"
repository = "https://github.com/LambdaAlpha/ui"
keywords = ["ai", "agi", "solver", "logic"]
categories = ["science"]

[lints]
workspace = true

[dependencies.ui]
path = "../lib"
version = "0.0.1"
